### ISSUE TITLE
What happens when article has fallen off

### ISSUE THREAD

**Issue by Reettaphant** [easter-egg-fun/shake#5]
Perhaps we should leave the space white for now and figure the rest later

**Comment by NataliaLKB** [comment]
Lets meet at brainstorm at 3pm regarding this? @tsop14 @Reettaphant @michaelwmcnamara

**Comment by michaelwmcnamara** [comment]
Things mentioned so far....
css scott essay;
animation showing history of guardian;
guardian utopia;
guardian codepen;

**Comment by tsop14** [comment]
Inception photo from hackday! :cyclone:

**Comment by NataliaLKB** [comment]
a Guardian literal easter egg! :egg:

**Comment by michaelwmcnamara** [comment]
as a backup - cp scotts essay here in pdf form - file:///Users/mmcnamara/Documents/tech%20front/cpscott100yrs.pdf
maybe we can convert to image or text

**Comment by NataliaLKB** [comment]
Liked our :egg:
